#page title
page_title: Hayatar # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6446906814 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: am # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://apps.apple.com/app/id6446906814
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Hayatar
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Elevate Your Armenian Typing Experience

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Arshak (f-person)
your_link: https://github.com/f-person
your_city: Yerevan 🇦🇲
email_address: hayatar@fperson.dev
facebook_username:
instagram_username:
twitter_username:
github_username: f-person
youtube_username: f-person
mastodon_link: https://fosstodon.org/@fperson

features:
  - title: Open-Source, Privacy-Centric
    description: Hayatar is <a href="https://github.com/f-person/hayatar">open-source</a> and respects your privacy by not collecting any data.
    fontawesome_icon_name: shield-alt

  - title: Native iOS Experience
    description: Designed with the intent of seamlessly integrating with your iOS device.
    fontawesome_icon_name: mobile

  - title: Spell Checking
    description: Offers real-time suggestions in Armenian, ensuring your messages are error-free.
    fontawesome_icon_name: spell-check

  - title: Customizable & Synced
    description: Customize the keyboard's behavior and settings, synced across all your iOS devices.
    fontawesome_icon_name: sync

  - title: Light & Dark Modes
    description: Supports both light and dark modes, ensuring your comfort and visibility.
    fontawesome_icon_name: adjust

  - title: Haptic & Sound Feedback
    description: Each key press provides subtle haptic feedback and satisfying sound.
    fontawesome_icon_name: volume-up

  - title: Callout Actions
    description: Quickly access all the symbols you need, including a dedicated number row.
    fontawesome_icon_name: keyboard

  - title: Beautiful Design
    description: A meticulously designed keyboard that combines aesthetics with functionality.
    fontawesome_icon_name: feather

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
